### ISSUE TITLE
Migrate to C#

### ISSUE THREAD

**Issue by DavidBeh** [Sepl9100/info11-jks#3]
java (boilerplate driven instant legacy code) nixgut

![image](https://user-images.githubusercontent.com/67109172/162636033-aea1c51d-36a2-4a77-a054-c6282a62d00c.png)

**Comment by Sepl9100** [comment]
python port

**Comment by DavidBeh** [comment]
🤢. Das würde dem ![goerg](https://user-images.githubusercontent.com/67109172/162642492-64ca845c-da3e-42a7-b9ae-81247d0bbcd8.png) aber auffallen
